import React from 'react';

const MediaGallery = () => {
  // Publicly available demo media (free to use)
  const videoUrl = 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4';
  const audioUrl = 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3';

  return (
    <div className="container mx-auto p-4">
      <h2 className="text-2xl font-bold mb-4 text-gray-800 dark:text-white">Course Media Gallery</h2>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        
        {/* Video Section */}
        <div className="border border-gray-300 dark:border-gray-700 rounded-lg overflow-hidden shadow-md bg-white dark:bg-gray-800">
          <video 
            src={videoUrl} 
            controls 
            className="w-full"
            preload="metadata"
          >
            Your browser does not support the video tag.
          </video>
          <div className="p-4">
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">Video: Big Buck Bunny</h3>
            <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
              A short animated film featuring a friendly bunny and three tiny creatures.
            </p>
          </div>
        </div>

        {/* Audio Section */}
        <div className="border border-gray-300 dark:border-gray-700 rounded-lg overflow-hidden shadow-md bg-white dark:bg-gray-800">
          <audio 
            src={audioUrl} 
            controls 
            className="w-full"
            preload="metadata"
          >
            Your browser does not support the audio element.
          </audio>
          <div className="p-4">
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">Audio: SoundHelix Song 1</h3>
            <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
              A royalty-free musical track generated by SoundHelix, perfect for learning.
            </p>
          </div>
        </div>

      </div>
    </div>
  );
};

export default MediaGallery;